version: '3.3'

services:
  redis:
    image: redis
    ports:
    - 6379:6379
    networks:
      - net

  webdis:
    image: 'anapsix/webdis'
    ports:
    - 7379:7379
    depends_on:
      - redis
    networks:
      - net

  scrapy:
    build:
      context: ./scrapy
    command: scrapy crawl quotes
    depends_on:
      - redis
    networks:
      - net

networks:
  net:
    driver: bridge
