version: '3.3'

services:
  redis:
    image: redis
    ports:
    - 6379:6379
    networks:
      - net

  flask:
    build:
      context: ./flask
    command: gunicorn -w4 -b 0.0.0.0:80 server:app
    depends_on:
      - redis
    ports:
    - 80:80
    networks:
      - net

  scrapy:
    build:
      context: ./scrapy
    command: python crawl.py
    depends_on:
      - redis
    networks:
      - net

networks:
  net:
    driver: bridge
